# Generated by Django 4.2 on 2024-06-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFamilyReuion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Gestionnaire'), (3, 'Utilisateur')], null=True),
        ),
    ]
