# Generated by Django 5.0.6 on 2024-06-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFamilyReuion', '0002_alter_personnel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='appFamilyReuion.agence'),
        ),
    ]
